package io.github.caimucheng.leaf.common.model

data class UnwrappedColorScheme(
//    val problemTypo: Int,
//    val problemWarning: Int,
//    val problemError: Int,
//    val attributeValue: Int,
//    val attributeName: Int,
//    val htmlTag: Int,
//    val annotation: Int,
//    val functionName: Int,
//    val identifierName: Int,
//    val identifierVar: Int,
//    val literal: Int,
//    val operator: Int,
//    val comment: Int,
//    val keyword: Int,
    val stickyScrollDivider: Int,
    val strikethrough: Int,
    val diagnosticTooltipAction: Int,
    val diagnosticTooltipDetailedMsg: Int,
    val diagnosticTooltipBriefMsg: Int,
    val diagnosticTooltipBackground: Int,
    val functionCharBackgroundStroke: Int,
    val hardWrapMarker: Int,
    val textInlayHintForeground: Int,
    val textInlayHintBackground: Int,
    val snippetBackgroundEditing: Int,
    val snippetBackgroundRelated: Int,
    val snippetBackgroundInactive: Int,
    val sideBlockLine: Int,
    val nonPrintableChar: Int,
    val textSelected: Int,
    val matchedTextBackground: Int,
    val completionWndCorner: Int,
    val completionWndBackground: Int,
    val completionWndTextPrimary: Int,
    val completionWndTextSecondary: Int,
    val completionWndItemCurrent: Int,
    val highlightedDelimitersBackground: Int,
    val highlightedDelimitersUnderline: Int,
    val highlightedDelimitersForeground: Int,
    val lineNumberPanelText: Int,
    val lineNumberPanel: Int,
    val blockLineCurrent: Int,
    val blockLine: Int,
    val scrollBarTrack: Int,
    val scrollBarThumbPressed: Int,
    val scrollBarThumb: Int,
    val underline: Int,
    val currentLine: Int,
    val selectionHandle: Int,
    val selectionInsert: Int,
    val selectedTextBackground: Int,
    val textNormal: Int,
    val wholeBackground: Int,
    val lineNumberBackground: Int,
    val lineNumberCurrent: Int,
    val lineNumber: Int,
    val lineDivider: Int
)