name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 'Get sdkVersion from versions.toml'
        id: read_version
        shell: bash
        run: |
          version=`perl -nlE 'say if s/compileSdkVersion \= \"(.*)\"/$1/g' gradle/libs.versions.toml`
          echo "sdkVersion=$version" >> $GITHUB_OUTPUT

      - name: 'Get cmakeVersion from versions.toml'
        id: read_version
        shell: bash
        run: |
          version=`perl -nlE 'say if s/cmakeVersion \= \"(.*)\"/$1/g' gradle/libs.versions.toml`
          echo "cmakeVersion=$version" >> $GITHUB_OUTPUT

      - name: 'Get ndkVersion from versions.toml'
        id: read_version
        shell: bash
        run: |
          version=`perl -nlE 'say if s/ndkVersion \= \"(.*)\"/$1/g' gradle/libs.versions.toml`
          echo "ndkVersion=$version" >> $GITHUB_OUTPUT
            
      - name: Setup Android SDK
        uses: amyu/setup-android@v4
        with:
          sdk-version: ${{ steps.read_version.outputs.sdkVersion }}
          cmake-version: ${{ steps.read_version.outputs.cmakeVersion }}
          ndk-version: ${{ steps.read_version.outputs.ndkVersion }}
          generate-job-summary: true

      - name: Accept Android SDK licenses
        run: yes | /usr/local/lib/android/sdk/tools/bin/sdkmanager --licenses
      
      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Build with gradle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-version: nightly
          arguments: assembleDebug

      - name: Upload debug apks
        uses: actions/upload-artifact@v3
        with:
          path: app/build/outputs/apk/debug/app-debug.apk

