name: Plugin CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build nodejs plugin debug APK
        uses: gradle/gradle-build-action@v2.4.2
        id: buildNodeJSDebug
        with:
          arguments: :plugin-nodejs:assembleDebug

      - name: Build nodejs plugin release APK
        uses: gradle/gradle-build-action@v2.4.2
        id: buildNodeJSRelease
        with:
          arguments: :plugin-nodejs:assembleRelease

      - name: Upload nodejs plugin debug APK artifact
        uses: actions/upload-artifact@v4
        if: ${{ always() && github.ref == 'refs/heads/master' && steps.buildNodeJSDebug.outcome == 'success' }}
        with:
          name: plugin-nodejs-debug
          path: plugin-nodejs/build/outputs/apk/debug/plugin-nodejs-debug.apk
          if-no-files-found: error

      - name: Upload nodejs plugin release APK artifact
        uses: actions/upload-artifact@v4
        if: ${{ always() && github.ref == 'refs/heads/master' && steps.buildNodeJSRelease.outcome == 'success' }}
        with:
          name: plugin-nodejs-release
          path: plugin-nodejs/build/outputs/apk/release/plugin-nodejs-release.apk
          if-no-files-found: error
